### PR TITLE
Bash for windows support

### PR DESCRIPTION
**Pull request by szenadam**
Tested on Windows 10 Pro and git version 2.19.1.windows.1.

### CODE REVIEW

**Comment by nandordudas** [comment]
Hello @szenadam, I have a question: how does it work, because the `security` command isn't exists on windows. Instead of `security` - on mac OS -, use `certutil` - on windows.

By example:
```sh
$ DOMAIN="app.local"
$ CRT_PATH="/c/Users/..."
$ certutil -delstore "Root" "${DOMAIN}"
$ certutil -f -addstore "Root" "${CRT_PATH}/${DOMAIN}.crt"
```

**Comment by szenadam** [comment]
Hello @nandordudas 
Thank you for the correction. I forgot to add the cert to the system-wide certifications. Windows 10 stores certifications in registry keys so I need to do a little research on that, test it out and then I will update my PR.

**Comment by nandordudas** [comment]
You'r welcome, here is one solution below:

https://gist.github.com/tpaksu/1a1c893bf23d3abc6ded45039bbe21d2

**Comment by kingkool68** [comment]
Thanks for the PR @szenadam and the contributions @nandordudas. I'm going to leave my original script as is instead of trying to support Windows with it. A more robust solution for self-signed SSL certs for local development is over at https://github.com/FiloSottile/mkcert

**Pull request closed without merging**
